version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: digital-notebook-postgres

    environment:
      POSTGRES_DB: digital_notebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5442:5432"

    volumes:
      - subject_postgres_data_catalog_db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d digital_notebook"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  auth-service:
    image: devshivmohan/note-book-api-services:latest
    pull_policy: always

    container_name: auth-service

    ports:
      - "8082:8082"

    volumes:
      - ./file-uploads:/app/file-uploads

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digital_notebook
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

volumes:
  subject_postgres_data_catalog_db: