name: PR Compilation Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "22"
          cache: gradle

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew clean compileJava build -x test
